"""服务模块导出。"""

from .config_service import (
    # 配置常量
    BOT_CONFIG,
    CONFIG_DIR,
    DATA_DIR,
    FACT_GUARD_CONFIG,
    PROMPT_CONFIG,
    PROJECT_ROOT,
    # bot 配置
    MAX_HISTORY_TURNS,
    MEME_API_URL,
    MEME_DELETE_KEYWORDS,
    MEME_SAVE_KEYWORDS,
    MEME_SEND_KEYWORDS,
    # memory_filter 配置
    SKIP_KEYWORDS,
    MIN_TEXT_LENGTH,
    QUESTION_MARKS,
    # behavior 配置
    W_CHAT,
    W_MEME,
    W_POKE,
    W_TOPIC,
    T_MEME_BOOST,
    T_POKE_BOOST,
    T_POKE_COOLDOWN_HOURS,
    B_MEME_STREAK,
    B_POKE_STREAK,
    D_EMOTION,
    # persona 配置
    BASE_SARCASM,
    BASE_GENTLENESS,
    BASE_MAX_CHARS,
    BANNED_CATCHPHRASES,
    LIKED_EXPRESSIONS,
    DISLIKED_EXPRESSIONS,
    # reflection 配置
    MAX_REFLECTIONS_PER_DAY,
    MAX_RECENT_REFLECTIONS,
    MESSAGES_BEFORE_REFLECTION,
    # active_life 配置
    ACTIVE_CHAT_MIN_INTERVAL_HOURS,
    ACTIVE_CHAT_MAX_INTERVAL_HOURS,
    ACTIVE_CHAT_PROBABILITY,
    BANNED_PHRASES,
    # 配置加载函数
    get_active_life_config,
    get_behavior_config,
    get_bot_config,
    get_config,
    get_fact_guard_config,
    get_human_behavior_config,
    get_memes_config,
    get_memory_filter_config,
    get_mood_config,
    get_persona_rules_config,
    get_prompt_config,
    get_reflection_config,
    get_relation_config,
    get_users_config,
)
from .db import get_connection, init_db
from .fact_guard import (
    check_risk_patterns,
    check_toxic,
    check_unsupported_claims,
    build_evidence_text,
    get_fallback_reply,
    get_toxic_fallback,
    parse_result,
    rewrite_unsafe_reply,
)
from .history import HistoryService
from .memory import MemoryService
from .meme_commands import MemeCommandHandler
from .meme_service import MemeService
from .mood import (
    MOOD_LABELS,
    NEGATIVE_KEYWORDS,
    POSITIVE_KEYWORDS,
    MoodService,
    REACTION_LONELINESS_DELTA,
    REACTION_NEGATIVE_MOOD_DELTA,
    REACTION_POSITIVE_MOOD_DELTA,
    REPLY_ENERGY_DELTA,
)
from .prompt_builder import PromptBuilder, build_user_message_with_time
from .relation import (
    NEGATIVE_FAVORABILITY_DELTA,
    POSITIVE_FAVORABILITY_DELTA,
    RELATION_NEGATIVE,
    RELATION_POSITIVE,
    REPLY_INTIMACY_DELTA,
    RelationshipService,
)
from .reflection import ReflectionService
from .social_memory import SocialMemoryService
from .active_chat_generator import ActiveChatGenerator, ConversationStarterService
from .reasoning import RelationshipReasoningService

__all__ = [
    # 配置常量
    "BOT_CONFIG",
    "CONFIG_DIR",
    "DATA_DIR",
    "FACT_GUARD_CONFIG",
    "PROMPT_CONFIG",
    "PROJECT_ROOT",
    "MAX_HISTORY_TURNS",
    "MEME_API_URL",
    "MEME_DELETE_KEYWORDS",
    "MEME_SAVE_KEYWORDS",
    "MEME_SEND_KEYWORDS",
    "SKIP_KEYWORDS",
    "MIN_TEXT_LENGTH",
    "QUESTION_MARKS",
    "W_CHAT",
    "W_MEME",
    "W_POKE",
    "W_TOPIC",
    "T_MEME_BOOST",
    "T_POKE_BOOST",
    "T_POKE_COOLDOWN_HOURS",
    "B_MEME_STREAK",
    "B_POKE_STREAK",
    "D_EMOTION",
    "BASE_SARCASM",
    "BASE_GENTLENESS",
    "BASE_MAX_CHARS",
    "BANNED_CATCHPHRASES",
    "LIKED_EXPRESSIONS",
    "DISLIKED_EXPRESSIONS",
    "MAX_REFLECTIONS_PER_DAY",
    "MAX_RECENT_REFLECTIONS",
    "MESSAGES_BEFORE_REFLECTION",
    "ACTIVE_CHAT_MIN_INTERVAL_HOURS",
    "ACTIVE_CHAT_MAX_INTERVAL_HOURS",
    "ACTIVE_CHAT_PROBABILITY",
    "BANNED_PHRASES",
    "TICK_INTERVAL",
    "LONELINESS_THRESHOLD",
    "ENERGY_THRESHOLD",
    "COOLDOWN_HOURS",
    "RECENT_HISTORY_TURNS",
    "BLOCKED_TARGETS",
    "POST_ACTION_ENERGY_DELTA",
    "POST_ACTION_LONELINESS_DELTA",
    # 配置函数
    "get_active_life_config",
    "get_behavior_config",
    "get_bot_config",
    "get_config",
    "get_fact_guard_config",
    "get_human_behavior_config",
    "get_memes_config",
    "get_memory_filter_config",
    "get_mood_config",
    "get_persona_rules_config",
    "get_prompt_config",
    "get_reflection_config",
    "get_relation_config",
    "get_users_config",
    # 数据库
    "get_connection",
    "init_db",
    # 事实闸门
    "check_risk_patterns",
    "check_toxic",
    "check_unsupported_claims",
    "build_evidence_text",
    "get_fallback_reply",
    "get_toxic_fallback",
    "parse_result",
    "rewrite_unsafe_reply",
    # 服务类
    "HistoryService",
    "MemoryService",
    "MemeCommandHandler",
    "MemeService",
    "MoodService",
    "PromptBuilder",
    "RelationshipService",
    "ReflectionService",
    "SocialMemoryService",
    "ActiveChatGenerator",
    "ConversationStarterService",
    "RelationshipReasoningService",
    "BehaviorService",
    "PersonaService",
    # 情绪常量
    "MOOD_LABELS",
    "NEGATIVE_KEYWORDS",
    "POSITIVE_KEYWORDS",
    "REACTION_LONELINESS_DELTA",
    "REACTION_NEGATIVE_MOOD_DELTA",
    "REACTION_POSITIVE_MOOD_DELTA",
    "REPLY_ENERGY_DELTA",
    # 关系常量
    "NEGATIVE_FAVORABILITY_DELTA",
    "POSITIVE_FAVORABILITY_DELTA",
    "RELATION_NEGATIVE",
    "RELATION_POSITIVE",
    "REPLY_INTIMACY_DELTA",
    # 提示词构建
    "build_user_message_with_time",
]
